# Assuming now that this makefile will be located in flux/scripts
RDIR= ~/git/flux
scriptDIR= $(RDIR)/scripts
functionDIR= $(RDIR)/functions
docDIR= $(RDIR)/docs
dataDIR= $(RDIR)/data
privDIR= $(RDIR)/data/private
 
# list script files
RSCRIPTS := $(wildcard $(scriptDIR)/*.R)
# pdf figures created by R
PDFFIGS := $(wildcard $(FIGDIR)/*.pdf)
# Indicator files to show R file has run
OUT_FILES:= $(RSCRIPTS:.R=.Rout)
  
# Dependencies:
weathermanipulations.R: gasexchange_pressuredata.R
pressuremanipulations.R: weathermanipulations.R
precipmanipulations-routines.R: $(functionDIR)/gasexchange_precipdata.R
co2_scenarios.R: pressuremanipulations.R $(functionDIR)/gasExchangeFlex.R $functionDIR/getmaunaloa.R $(PRIVDIR)/salcalc.R
co2ExplVar.R: co2_scenarios.R weathermanipulations.R

regression_routines.R: co2ExplVar.R co2_scenarios.R 
regression_routines_eachlake: regression_routines.R

# run script files
R CMD BATCH RSCRIPTS

# RUN EVERY R FILE
$(RDIR)/%.Rout: $(RDIR)/%.R $(RDIR)/functions.R
	R CMD BATCH $<
  
# Run R files
R: $(OUT_FILES)
 
# View main tex file
view: $(TEXFILE).pdf
	evince $(TEXFILE).pdf &
 
# Clean up stray files
clean:
	rm -fv $(OUT_FILES) 
	rm -fv $(CROP_FILES)
	rm -fv *.aux *.log *.toc *.blg *.bbl *.synctex.gz
	rm -fv *.out *.bcf *blx.bib *.run.xml
	rm -fv *.fdb_latexmk *.fls
	rm -fv $(TEXFILE).pdf
 
.PHONY: all clean
